document.writeln("<div class=\'con footer-contaienr\'>");
document.writeln("			<div class=\'footer-left\'>");
document.writeln("				<div class=\'footer-left-title\'>联系我们</div>");
document.writeln("				<div class=\'footer-left-cell\'>");
document.writeln("					<img src=\'https://magicdn.oss-cn-beijing.aliyuncs.com/www/20190830/lianxidianhua.svg\'>");
document.writeln("					联系电话: 010-86462395");
document.writeln("				</div>");
document.writeln("				<div class=\'footer-left-cell\'>");
document.writeln("					<img src=\'https://magicdn.oss-cn-beijing.aliyuncs.com/www/20190830/weixin.svg\'>");
document.writeln("					客服微信: magilink");
document.writeln("				</div>");
document.writeln("				<div class=\'footer-left-cell\'>");
document.writeln("					<img src=\'https://magicdn.oss-cn-beijing.aliyuncs.com/www/20190830/youxiang.svg\'>");
document.writeln("						合作邮箱: gongxiang@magi.link<span>pr邮箱：pr@magi.link</span>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("			<div class=\'footer-right mt60\'>");
document.writeln("				<div class=\'footer-left\'>");
document.writeln("					<img src=\'img/subaomini.png\'>");
document.writeln("					微信小程序 - 麦极宿宝");
document.writeln("				</div>");
document.writeln("				<div class=\'footer-left ml100\'>");
document.writeln("					<img src=\'img/baojie.png\'>");
document.writeln("					微信小程序 - 麦极服务保洁端 ");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("		<div class=\'footer-copy\'>Copyright © 北京空间共享科技有限公司 | 京ICP备19008156号</div>");